// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyASpYsRffzuXLRhPNrimW14v-A3B0XZTBo',
    appId: '1:18402451667:web:f4e278d24270e916e97426',
    messagingSenderId: '18402451667',
    projectId: 'tc2007b-nativo',
    authDomain: 'tc2007b-nativo.firebaseapp.com',
    storageBucket: 'tc2007b-nativo.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDG2MJBUpicIj3kBkW3F-29D5d3z7xaemg',
    appId: '1:18402451667:android:d5d6de3525a9f746e97426',
    messagingSenderId: '18402451667',
    projectId: 'tc2007b-nativo',
    storageBucket: 'tc2007b-nativo.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyABlGzrzn7SWBX2rmdoHUGY2OBlr993-qA',
    appId: '1:18402451667:ios:c43bd8c89267071ae97426',
    messagingSenderId: '18402451667',
    projectId: 'tc2007b-nativo',
    storageBucket: 'tc2007b-nativo.appspot.com',
    iosBundleId: 'com.example.theVetApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyABlGzrzn7SWBX2rmdoHUGY2OBlr993-qA',
    appId: '1:18402451667:ios:1094c2d27724a6f5e97426',
    messagingSenderId: '18402451667',
    projectId: 'tc2007b-nativo',
    storageBucket: 'tc2007b-nativo.appspot.com',
    iosBundleId: 'com.example.theVetApp.RunnerTests',
  );
}
